// Code generated by benzene-codegen. DO NOT EDIT.

package paymentscapture

import (
	"context"
	"encoding/json"

	benzene "github.com/daniellepelley/benzene-go"
	"github.com/daniellepelley/benzene-go/client"
	"github.com/daniellepelley/benzene-go/httpclient"
)

// ContractHash is the contract-document.md §6 contractHash this client was generated
// from - compare it against the producing service's own hash to detect drift.
const ContractHash = "sha256:1520b2c06e9f4095f5cd993cd2a4f5ffe3b71dc0ce64f60d5e895cb269934584"

// RequiredTopics is every topic this client sends, for a consumer's own outbound-routing
// wiring or startup validation.
var RequiredTopics = []benzene.Topic{
	{ID: "payments:capture"},
}

// PaymentsCaptureClient is a generated client scoped to RequiredTopics, over client.Sender.
type PaymentsCaptureClient struct {
	sender client.Sender
}

// NewPaymentsCaptureClient constructs a PaymentsCaptureClient over sender.
func NewPaymentsCaptureClient(sender client.Sender) *PaymentsCaptureClient {
	return &PaymentsCaptureClient{sender: sender}
}

// CapturePayments sends payments:capture.
func (c *PaymentsCaptureClient) CapturePayments(ctx context.Context, req CapturePayment) (benzene.Result[PaymentDto], error) {
	return c.CapturePaymentsWithHeaders(ctx, req, nil)
}

// CapturePaymentsWithHeaders is CapturePayments with caller-supplied outbound headers.
func (c *PaymentsCaptureClient) CapturePaymentsWithHeaders(ctx context.Context, req CapturePayment, headers map[string]string) (benzene.Result[PaymentDto], error) {
	body, err := json.Marshal(req)
	if err != nil {
		return benzene.Result[PaymentDto]{}, err
	}
	raw := c.sender.Send(ctx, benzene.Topic{ID: "payments:capture"}, headers, body)
	return httpclient.Unmarshal[PaymentDto](raw)
}
