// Code generated by benzene-codegen. DO NOT EDIT.

package paymentscapture

type CapturePayment struct {
	Amount   *float64 `json:"Amount,omitempty"`
	Currency string   `json:"Currency"`
	OrderId  string   `json:"OrderId"`
}

type PaymentDto struct {
	Amount   *float64 `json:"Amount,omitempty"`
	Currency *string  `json:"Currency,omitempty"`
	Id       *string  `json:"Id,omitempty"`
	OrderId  *string  `json:"OrderId,omitempty"`
	Status   *string  `json:"Status,omitempty"`
}
