package gengo

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/daniellepelley/benzene-go/codegen/contractdoc"
)

// ServiceOptions configures GenerateServiceClient.
type ServiceOptions struct {
	// ServiceName names the generated client type ("Payments" -> PaymentsClient,
	// NewPaymentsClient), mirroring MessageClientSdkBuilder's ServiceName. Required.
	ServiceName string
	// PackageName is the Go package name for the generated files, used exactly (must be a legal
	// Go identifier - see ValidateGoIdentifier). Required.
	PackageName string
	// TopicScoped selects contractdoc.Hash's topicScoped parameter: true only for a §5.3
	// single-topic (atomic) client built over a TopicScopedProjection document (see atomic.go);
	// false (the default) for every other shape, including a service-level client filtered by
	// an include-list - matching the .NET reference exactly (MessageClientSdkBuilder's
	// IsTopicScopedForHash is always false; only AtomicClientSdkBuilder's inner options set it
	// true), since contract-document.md §6.2's whole-service reserved-entry strip applies to any
	// non-topic-scoped projection regardless of how its requests[] were filtered.
	TopicScoped bool
}

// GeneratedFile is one output source file.
type GeneratedFile struct {
	// Name is the file's base name, e.g. "client.go".
	Name string
	// Source is the file's full, gofmt'd Go source.
	Source string
}

// GenerateServiceClient generates a service-level client (contract-document.md §5's service
// shape: one Go type, one method per doc's in-scope request topic) from doc, which the caller has
// already scoped as it wants (contractdoc.ApplyScope for the default/include-list shape,
// contractdoc.TopicScopedProjection for the §5.3 single-topic shape - see GenerateAtomicClients).
// Two files are returned: "types.go" (one struct per doc.Schemas() entry) and "client.go" (the
// client type, its constructor, RequiredTopics, and one method pair per request topic).
func GenerateServiceClient(doc *contractdoc.Document, opts ServiceOptions) ([]GeneratedFile, error) {
	if err := ValidateGoIdentifier(opts.PackageName); err != nil {
		return nil, fmt.Errorf("gengo: PackageName: %w", err)
	}
	if opts.ServiceName == "" {
		return nil, fmt.Errorf("gengo: ServiceName is required")
	}

	hash, err := contractdoc.Hash(doc, opts.TopicScoped)
	if err != nil {
		return nil, fmt.Errorf("gengo: contract hash: %w", err)
	}

	schemas := doc.Schemas()
	typeDecls, err := BuildTypeDecls(schemas)
	if err != nil {
		return nil, err
	}

	usesTime := false
	for _, d := range typeDecls {
		usesTime = usesTime || d.UsesTime
	}

	typesSrc, err := formatSource(buildTypesFile(opts.PackageName, typeDecls, usesTime))
	if err != nil {
		return nil, fmt.Errorf("gengo: formatting types.go: %w", err)
	}

	clientBody, err := buildClientFile(opts.PackageName, opts.ServiceName, hash, doc.Requests(), schemas)
	if err != nil {
		return nil, err
	}
	clientSrc, err := formatSource(clientBody)
	if err != nil {
		return nil, fmt.Errorf("gengo: formatting client.go: %w", err)
	}

	return []GeneratedFile{
		{Name: "types.go", Source: typesSrc},
		{Name: "client.go", Source: clientSrc},
	}, nil
}

func formatSource(src string) (string, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("%w\n---\n%s", err, src)
	}
	return string(out), nil
}

const generatedHeader = "// Code generated by benzene-codegen. DO NOT EDIT.\n"

func buildTypesFile(pkg string, decls []TypeDecl, usesTime bool) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	fmt.Fprintf(&b, "\npackage %s\n\n", pkg)
	if usesTime {
		b.WriteString("import \"time\"\n\n")
	}
	for i, d := range decls {
		if i > 0 {
			b.WriteString("\n\n")
		}
		b.WriteString(d.Source)
	}
	b.WriteString("\n")
	return b.String()
}

func buildClientFile(pkg, serviceName, hash string, requests []map[string]any, catalogue map[string]any) (string, error) {
	clientType := FormatGoName(serviceName) + "Client"

	var b strings.Builder
	b.WriteString(generatedHeader)
	fmt.Fprintf(&b, "\npackage %s\n\n", pkg)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\t\"encoding/json\"\n\n")
	b.WriteString("\tbenzene \"github.com/daniellepelley/benzene-go\"\n")
	b.WriteString("\t\"github.com/daniellepelley/benzene-go/client\"\n")
	b.WriteString("\t\"github.com/daniellepelley/benzene-go/httpclient\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// ContractHash is the contract-document.md §6 contractHash this client was generated\n// from - compare it against the producing service's own hash to detect drift.\nconst ContractHash = %q\n\n", hash)

	b.WriteString("// RequiredTopics is every topic this client sends, for a consumer's own outbound-routing\n// wiring or startup validation.\n")
	b.WriteString("var RequiredTopics = []benzene.Topic{\n")
	for _, r := range requests {
		fmt.Fprintf(&b, "\t%s,\n", topicLiteralElem(r))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// %s is a generated client scoped to RequiredTopics, over client.Sender.\ntype %s struct {\n\tsender client.Sender\n}\n\n", clientType, clientType)
	fmt.Fprintf(&b, "// New%s constructs a %s over sender.\nfunc New%s(sender client.Sender) *%s {\n\treturn &%s{sender: sender}\n}\n", clientType, clientType, clientType, clientType, clientType)

	methodNames := map[string]string{}
	for _, r := range requests {
		topic := contractdoc.RequestTopic(r)
		methodName := TopicReversedMethodName(topic)
		if collidesWith, exists := methodNames[methodName]; exists {
			return "", fmt.Errorf("gengo: topics %q and %q both derive the method name %q", collidesWith, topic, methodName)
		}
		methodNames[methodName] = topic

		reqSchema, _ := r["request"].(map[string]any)
		respSchema, _ := r["response"].(map[string]any)
		reqType := GoTypeName(reqSchema, catalogue)
		respType := GoTypeName(respSchema, catalogue)
		topicExpr := topicLiteral(r)

		fmt.Fprintf(&b, "\n// %s sends %s.\nfunc (c *%s) %s(ctx context.Context, req %s) (benzene.Result[%s], error) {\n\treturn c.%sWithHeaders(ctx, req, nil)\n}\n",
			methodName, topic, clientType, methodName, reqType, respType, methodName)
		fmt.Fprintf(&b, "\n// %sWithHeaders is %s with caller-supplied outbound headers.\nfunc (c *%s) %sWithHeaders(ctx context.Context, req %s, headers map[string]string) (benzene.Result[%s], error) {\n\tbody, err := json.Marshal(req)\n\tif err != nil {\n\t\treturn benzene.Result[%s]{}, err\n\t}\n\traw := c.sender.Send(ctx, %s, headers, body)\n\treturn httpclient.Unmarshal[%s](raw)\n}\n",
			methodName, methodName, clientType, methodName, reqType, respType, respType, topicExpr, respType)
	}

	return b.String(), nil
}

// topicLiteralElem renders a benzene.Topic value for a []benzene.Topic composite-literal element
// position, where Go infers the element type and repeating it (gofmt -s's S1016) is redundant.
func topicLiteralElem(r map[string]any) string {
	topic := contractdoc.RequestTopic(r)
	if version, present := contractdoc.RequestVersion(r); present && version != "" {
		return fmt.Sprintf("{ID: %q, Version: %q}", topic, version)
	}
	return fmt.Sprintf("{ID: %q}", topic)
}

// topicLiteral renders a standalone benzene.Topic{...} value expression, e.g. as an argument to
// client.Sender.Send.
func topicLiteral(r map[string]any) string {
	return "benzene.Topic" + topicLiteralElem(r)
}
